### PR TITLE
Add and remove layers

### PR DESCRIPTION
**Pull request by teknofire**

### CODE REVIEW

**Comment by grimm** [comment]
Do we also want to have the layers disappear from the modal when they are selected?

**Comment by grimm** [comment]
I was able to fix all but two of the rubocop errors, the remaining errors are going to need some restructuring of the code or changing the rubocop settings.  

Offenses:

app/channels/workspaces_channel.rb:13:3: C: Assignment Branch Condition size for receive is too high. [25.02/20]
  def receive(data)
  ^^^
app/controllers/view_layers_controller.rb:31:3: C: Assignment Branch Condition size for create is too high. [24.04/20]
  def create
  ^^^

83 files inspected, 2 offenses detected

**Comment by grimm** [comment]
ready for review

**Comment by teknofire** [comment]
This is all now in the PR #37

**Pull request closed without merging**
